#!/usr/bin/env bash
# Контракт rename-client и stats — двух команд, которые бот вызывает чаще
# остальных: первую по кнопке, вторую раз в минуту для снимка.
#
# Проверяется без root и без WireGuard: состояние живёт во временном каталоге
# через GROXY_DIR, `wg` подменён. Запуск:
#   bash tests/bridge-stats.sh
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPROOT="$(mktemp -d)"
export GROXY_DIR="${TMPROOT}/groxy"
export GROXY_WG_DIR="${TMPROOT}/wg"
mkdir -p "${GROXY_WG_DIR}"
GROXY_VERSION='test'

mkdir -p "${GROXY_DIR}/bridge/wg0/clients"
mkdir -p "${GROXY_DIR}/bridge/portals/nether"
cat > "${GROXY_DIR}/bridge/wg0/server.env" <<EOF
SUBNET=10.66.66.0/24
LISTEN_PORT=51820
PUBLIC_IP=203.0.113.1
EOF

# Ключи обязаны иметь настоящую форму: 43 символа base64 плюс '='. Иначе
# _json_key печатает пустую строку, и проверка «ключ доехал до JSON»
# прошла бы на любом мусоре.
fake_key() { printf 'fakekey%036d=' "$1"; }

PORTAL_KEY="$(fake_key 700)"
cat > "${GROXY_DIR}/bridge/portals/nether/portal.env" <<EOF
PORTAL_NAME=nether
PORTAL_ENDPOINT=198.51.100.7
PORTAL_PORT=61285
PORTAL_PUBKEY=${PORTAL_KEY}
TUNNEL_SUBNET=10.77.77.0/24
TUNNEL_PORTAL_IP=10.77.77.1
TUNNEL_BRIDGE_IP=10.77.77.2
EOF
printf 'nether\n' > "${GROXY_DIR}/bridge/current-portal"

ALPHA_KEY="$(fake_key 1)"
BETA_KEY="$(fake_key 2)"
GAMMA_KEY="$(fake_key 3)"
make_peer() {
    local name="$1" addr="$2" key="$3"
    cat > "${GROXY_DIR}/bridge/wg0/clients/${name}.peer" <<EOF
# client "${name}" — generated by groxy test
PSK=$(fake_key 500)
ADDR=${addr}
PUBLIC_KEY=${key}
EOF
    chmod 600 "${GROXY_DIR}/bridge/wg0/clients/${name}.peer"
}
make_peer alpha 10.66.66.2 "${ALPHA_KEY}"
make_peer beta  10.66.66.3 "${BETA_KEY}"
make_peer gamma 10.66.66.4 "${GAMMA_KEY}"

# shellcheck source=/dev/null
source "${REPO}/lib/common.sh"
# shellcheck source=/dev/null
source "${REPO}/lib/wireguard.sh"
# shellcheck source=/dev/null
source "${REPO}/lib/system.sh"
# shellcheck source=/dev/null
source "${REPO}/lib/status.sh"
# shellcheck source=/dev/null
source "${REPO}/lib/bridge_wg0.sh"

# --- подмены внешнего мира ------------------------------------------------
require_root() { :; }
acquire_state_lock() { :; }

CALLS="${TMPROOT}/calls"
mkdir -p "${CALLS}"
count_of() { find "${CALLS}" -name "$1.*" | wc -l | tr -d ' '; }
reset_calls() { rm -f "${CALLS}"/*; }
wg_sync_peers() { : > "${CALLS}/sync.$$.${RANDOM}"; }
bridge_render_wg0_conf() { : > "${CALLS}/render.$$.${RANDOM}"; }

# `wg show <iface> dump`. Первая строка описывает интерфейс — команда обязана
# её отбросить, иначе приватный ключ уедет в вывод. Поэтому она здесь есть и
# выглядит правдоподобно.
#
# Три случая, все взяты с живого узла:
#   alpha — подключён, endpoint и счётчики на месте;
#   gamma — есть в ядре, но ни разу не подключался: wg пишет `(none)` в поле
#           endpoint и нули дальше. Именно так выглядит только что выданный
#           профиль, и это самый частый вид записи в первые дни;
#   beta  — в дампе отсутствует вовсе. Так выглядит пир, снятый с ядра, пока
#           файл ещё лежит на диске.
# Колонки: ключ, PSK, endpoint, allowed-ips, handshake, принято, отдано,
# keepalive — порядок сверен с `wg show wg0 dump | cat -A` на moscow-25000-01.
NOW_HS=1757000000
wg() {
    [[ "$1" == 'show' ]] || return 0
    case "$2" in
        wg0)
            printf 'privkeyplaceholder\tpubkeyplaceholder\t51820\toff\n'
            printf '%s\t%s\t192.0.2.5:1234\t10.66.66.2/32\t%s\t1024\t2048\toff\n' \
                "${ALPHA_KEY}" "$(fake_key 501)" "${NOW_HS}"
            printf '%s\t%s\t(none)\t10.66.66.4/32\t0\t0\t0\toff\n' \
                "${GAMMA_KEY}" "$(fake_key 502)"
            ;;
        wg1)
            printf 'privkeyplaceholder\tpubkeyplaceholder\t40609\toff\n'
            printf '%s\t%s\t198.51.100.7:61285\t0.0.0.0/0\t%s\t4096\t8192\t25\n' \
                "${PORTAL_KEY}" "$(fake_key 503)" "${NOW_HS}"
            ;;
    esac
}

pass=0; fail=0; skipped=0
have_python=0
command -v python3 >/dev/null && have_python=1
check() {
    local what="$1" want="$2" got="$3"
    if [[ "${want}" == "${got}" ]]; then
        printf '  ok   %s\n' "${what}"; pass=$((pass + 1))
    else
        printf '  FAIL %s: want %q, got %q\n' "${what}" "${want}" "${got}"
        fail=$((fail + 1))
    fi
}

jq_field() {
    python3 -c 'import json,sys
d = json.load(sys.stdin)
for k in sys.argv[1:]:
    d = d[int(k)] if isinstance(d, list) else d[k]
print("null" if d is None else d)' "$@" 2>/dev/null
}

echo "== stats --json =="
out=$(bridge_stats --json 2>/dev/null)
check "ровно одна строка" 1 "$(wc -l <<<"${out}" | tr -d ' ')"
check "приватный ключ интерфейса не попал в вывод" 0 \
    "$(grep -c 'privkeyplaceholder' <<<"${out}")"
if (( have_python )); then
    check "валидный JSON" ok \
        "$(python3 -c 'import json,sys; json.load(sys.stdin); print("ok")' <<<"${out}")"
    check "все три клиента на месте" 3 "$(python3 -c 'import json,sys; print(len(json.load(sys.stdin)["clients"]))' <<<"${out}")"
    check "имя портала" nether "$(jq_field portal name <<<"${out}")"
    check "handshake портала сырой эпохой" "${NOW_HS}" "$(jq_field portal latest_handshake <<<"${out}")"
    check "счётчики портала" 4096 "$(jq_field portal rx <<<"${out}")"
    # Адрес портала внутри туннеля нужен боту, чтобы прочитать reporter.
    # Читать его самому из /etc/groxy бот не может: каталог bridge/ имеет
    # права 700, там приватный ключ, и отказ выглядел бы как «портал не
    # настроен» — то есть как исправная работа.
    check "адрес портала в туннеле отдан" 10.77.77.1 "$(jq_field portal tunnel_address <<<"${out}")"
    # Состояние классификатора отдаёт CLI, а не бот чтением /etc/groxy:
    # каталог bridge/ имеет права 700, и попытка прочесть его молча не
    # удавалась, выглядя как «выключен» — то есть как норма.
    check "состояние классификатора отдано" off "$(jq_field classifier <<<"${out}")"
    check "endpoint подключённого клиента" '192.0.2.5:1234' "$(jq_field clients 0 endpoint <<<"${out}")"
    # IPv6 wg пишет со скобками. Класс символов, пропускающий IPv4 и
    # спотыкающийся на скобках, отдал бы null и показал живого клиента
    # отключённым — проверяется отдельно именно поэтому.
    check "endpoint в форме IPv6" ok "$(_json_endpoint '[2001:db8::1]:51820' | grep -c . | sed 's/^1$/ok/')"
    check "IPv6 не превратился в null" 0 \
        "$(_json_endpoint '[2001:db8::1]:51820' | grep -c '^null$')"
    check "кавычка в endpoint отвергнута" 1 \
        "$(_json_endpoint 'a"b' | grep -c '^null$')"
    check "handshake подключённого клиента" "${NOW_HS}" "$(jq_field clients 0 latest_handshake <<<"${out}")"
    # Клиента нет в дампе ядра — это не ошибка и не пропуск записи: профиль
    # существует, просто им ни разу не пользовались. Нули и null здесь
    # означают именно это, и бот по ним рисует «не подключался».
    check "клиент без записи в ядре: endpoint null" null "$(jq_field clients 1 endpoint <<<"${out}")"
    check "клиент без записи в ядре: handshake ноль" 0 "$(jq_field clients 1 latest_handshake <<<"${out}")"
    check "клиент без записи в ядре: счётчики нули" 0 "$(jq_field clients 1 rx <<<"${out}")"
    # Пир в ядре есть, подключений не было: wg пишет туда `(none)`. Скобки не
    # проходят класс символов и так, но случай проверяется отдельно — иначе
    # правильность держалась бы на том, что никто не добавит скобки в класс
    # ради очередного формата адреса.
    check "пир в ядре без подключений: endpoint null" null "$(jq_field clients 2 endpoint <<<"${out}")"
    check "пир в ядре без подключений: handshake ноль" 0 "$(jq_field clients 2 latest_handshake <<<"${out}")"
    check "строка (none) не просочилась в вывод" 0 "$(grep -c '(none)' <<<"${out}")"
else
    skipped=$((skipped + 6))
fi

echo "== включённый классификатор виден в снимке =="
printf 'XRAY_CLASSIFIER=on\n' > "${GROXY_DIR}/bridge/settings.env"
out=$(bridge_stats --json 2>/dev/null)
if (( have_python )); then
    check "классификатор on" on "$(jq_field classifier <<<"${out}")"
else
    skipped=$((skipped + 1))
fi
rm -f "${GROXY_DIR}/bridge/settings.env"

echo "== stats по одному клиенту =="
out=$(bridge_stats beta --json 2>/dev/null)
if (( have_python )); then
    check "ровно одна запись" 1 "$(python3 -c 'import json,sys; print(len(json.load(sys.stdin)["clients"]))' <<<"${out}")"
    check "именно запрошенный" beta "$(jq_field clients 0 name <<<"${out}")"
else
    skipped=$((skipped + 2))
fi

echo "== посторонний файл не ломает разбор всего ответа =="
: > "${GROXY_DIR}/bridge/wg0/clients/ev\"il.peer"
out=$(bridge_stats --json 2>/dev/null)
if (( have_python )); then
    check "JSON остаётся валидным" ok \
        "$(python3 -c 'import json,sys; json.load(sys.stdin); print("ok")' <<<"${out}")"
    check "живые клиенты не потеряны" 3 "$(python3 -c 'import json,sys; print(len(json.load(sys.stdin)["clients"]))' <<<"${out}")"
else
    skipped=$((skipped + 2))
fi
rm -f "${GROXY_DIR}/bridge/wg0/clients/ev\"il.peer"

echo "== портала нет — поле null, а не пропущенное =="
mv "${GROXY_DIR}/bridge/current-portal" "${TMPROOT}/current-portal.bak"
out=$(bridge_stats --json 2>/dev/null)
if (( have_python )); then
    check "portal равен null" null "$(jq_field portal <<<"${out}")"
    check "клиенты всё равно отданы" 3 "$(python3 -c 'import json,sys; print(len(json.load(sys.stdin)["clients"]))' <<<"${out}")"
else
    skipped=$((skipped + 2))
fi
mv "${TMPROOT}/current-portal.bak" "${GROXY_DIR}/bridge/current-portal"

echo "== интерфейс не поднят =="
# `wg show` на отсутствующем интерфейсе возвращает 1. Под `set -euo pipefail`,
# с которым работает диспетчер, это убивало весь процесс: снимок пропадал
# ровно тогда, когда туннель до портала лёг. Проверка запускается через bash
# -c именно с `-e`, потому что сам набор тестов идёт без него и прошлую версию
# пропустил.
cat > "${TMPROOT}/probe-down.sh" <<'PROBE'
# Запускается отдельным bash с -e, чтобы воспроизвести условия диспетчера.
# Имя неподнятого интерфейса приходит первым аргументом.
set -euo pipefail
IFACE_DOWN="$1"
source "${REPO}/lib/common.sh"
source "${REPO}/lib/system.sh"
source "${REPO}/lib/status.sh"
source "${REPO}/lib/bridge_wg0.sh"
require_root() { :; }
wg() {
    [[ "$1" == 'show' ]] || return 0
    [[ "$2" == "${IFACE_DOWN}" ]] && return 1
    printf 'priv\tpub\t51820\toff\n'
}
bridge_stats --json
PROBE

# GROXY_DIR и GROXY_WG_DIR уже экспортированы наверху и объявлены readonly
# в common.sh, поэтому передаётся только REPO.
probe_down() {
    REPO="${REPO}" bash "${TMPROOT}/probe-down.sh" "$1" 2>/dev/null
}

out=$(probe_down wg1); rc=$?
check "wg1 не поднят — команда не падает" 0 "${rc}"
if (( have_python )); then
    check "wg1 не поднят — JSON всё равно валиден" ok \
        "$(python3 -c 'import json,sys; json.load(sys.stdin); print("ok")' <<<"${out}" 2>/dev/null)"
else
    skipped=$((skipped + 1))
fi

out=$(probe_down wg0); rc=$?
check "wg0 не поднят — команда не падает" 0 "${rc}"

echo "== секрет портала не утекает в окружение =="
# portal.env читается через source, и поле, не объявленное локальным, остаётся
# жить в вызывающей области. Для PSK это преобщий ключ туннеля до портала.
PSK='не тронуто'
bridge_stats --json >/dev/null 2>&1
check "PSK не подменён содержимым portal.env" 'не тронуто' "${PSK}"

echo "== stats не берёт блокировку =="
# Читающая команда, которая ждёт общей блокировки, останавливает наблюдение
# ровно на время долгой правки. Подменяем acquire_state_lock на отказ: если
# stats её вызовет, команда упадёт.
acquire_state_lock() { return 1; }
( bridge_stats --json ) >/dev/null 2>&1; rc=$?
check "код возврата 0 при недоступной блокировке" 0 "${rc}"
acquire_state_lock() { :; }

echo "== переименование =="
reset_calls
bridge_rename_client alpha alpha-new >/dev/null 2>&1; rc=$?
check "код возврата" 0 "${rc}"
check "старого файла нет" 0 \
    "$(find "${GROXY_DIR}/bridge/wg0/clients" -name 'alpha.peer' | wc -l | tr -d ' ')"
check "новый файл есть" 1 \
    "$(find "${GROXY_DIR}/bridge/wg0/clients" -name 'alpha-new.peer' | wc -l | tr -d ' ')"
check "конфиг перерендерен" 1 "$(count_of render)"
check "ядро синхронизировано" 1 "$(count_of sync)"
# Ключ обязан пережить переименование: на нём держится соединение клиента.
check "публичный ключ не изменился" "${ALPHA_KEY}" \
    "$(peer_field "${GROXY_DIR}/bridge/wg0/clients/alpha-new.peer" PUBLIC_KEY)"
check "комментарий внутри файла обновлён" 1 \
    "$(grep -c '^# client "alpha-new"' "${GROXY_DIR}/bridge/wg0/clients/alpha-new.peer")"
check "права файла пира сохранены" 600 \
    "$(stat -f '%Lp' "${GROXY_DIR}/bridge/wg0/clients/alpha-new.peer" 2>/dev/null \
        || stat -c '%a' "${GROXY_DIR}/bridge/wg0/clients/alpha-new.peer")"

echo "== переименование в занятое имя =="
( bridge_rename_client alpha-new beta ) >/dev/null 2>&1; rc=$?
check "отдельный код 10, а не общий 1" 10 "${rc}"
check "занятый файл не тронут" "${BETA_KEY}" \
    "$(peer_field "${GROXY_DIR}/bridge/wg0/clients/beta.peer" PUBLIC_KEY)"
check "исходный файл на месте" 1 \
    "$(find "${GROXY_DIR}/bridge/wg0/clients" -name 'alpha-new.peer' | wc -l | tr -d ' ')"

echo "== повтор после успешного переименования =="
# Бот потерял ответ по таймауту и повторяет команду. Старого имени уже нет,
# новое есть — работа сделана, это успех.
reset_calls
( bridge_rename_client alpha alpha-new ) >/dev/null 2>&1; rc=$?
check "повтор — успех" 0 "${rc}"
check "лишнего рендера не было" 0 "$(count_of render)"

echo "== переименование несуществующего =="
( bridge_rename_client nosuch other ) >/dev/null 2>&1; rc=$?
check "отказ, а не молчаливый успех" 1 "${rc}"

echo "== имя в самого себя =="
reset_calls
( bridge_rename_client beta beta ) >/dev/null 2>&1; rc=$?
check "успех" 0 "${rc}"
check "ничего не перерендерено" 0 "$(count_of render)"

echo "== недопустимое новое имя =="
( bridge_rename_client beta '../escape' ) >/dev/null 2>&1; rc=$?
check "отказ" 1 "${rc}"
check "файл не уехал за пределы каталога" 0 \
    "$(find "${GROXY_DIR}/bridge/wg0" -maxdepth 1 -name 'escape*' | wc -l | tr -d ' ')"

echo
if (( skipped )); then
    echo "прошло: ${pass}, упало: ${fail}, ПРОПУЩЕНО: ${skipped}"
else
    echo "прошло: ${pass}, упало: ${fail}"
fi
rm -rf "${TMPROOT}"
[[ ${fail} -eq 0 ]]
