#!/usr/bin/env bash
# Контракт реестра пиров на портале. Запуск:
#   bash tests/portal-bridges.sh
#
# Без root и без WireGuard: состояние во временном каталоге, внешние вызовы
# подменены.
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPROOT="$(mktemp -d)"
export GROXY_DIR="${TMPROOT}/groxy"
export GROXY_WG_DIR="${TMPROOT}/wg"
mkdir -p "${GROXY_WG_DIR}" "${GROXY_DIR}/portal/bridges"
GROXY_VERSION='test'

fake_key() { printf 'fakekey%036d=' "$1"; }
printf '%s\n' "$(fake_key 900)" > "${GROXY_DIR}/portal/private.key"
printf '%s\n' "$(fake_key 901)" > "${GROXY_DIR}/portal/public.key"
cat > "${GROXY_DIR}/portal/server.env" <<EOF
PUBLIC_IP=198.51.100.7
LISTEN_PORT=61285
TUNNEL_SUBNET=10.77.77.0/24
EGRESS_IFACE=ens3
EOF

# shellcheck source=/dev/null
source "${REPO}/lib/common.sh"
# shellcheck source=/dev/null
source "${REPO}/lib/wireguard.sh"
# shellcheck source=/dev/null
source "${REPO}/lib/system.sh"
# shellcheck source=/dev/null
source "${REPO}/lib/portal.sh"

require_root() { :; }
acquire_state_lock() { :; }
portal_render_wg0_conf() { : > "${TMPROOT}/rendered"; }
# Синхронизация, а не перезапуск: правка реестра пиров на портале не должна
# рвать туннели подключённых бриджей.
wg_sync_peers() { : > "${TMPROOT}/synced"; }
wg_quick_enable_restart() { : > "${TMPROOT}/restarted"; }
ensure_conntrack_capacity() { :; }
iptables() { :; }
_n=0
wg() {
    case "${1:-}" in
        genpsk|genkey) _n=$((_n + 1)); printf 'fakekey%036d=\n' "$((500 + _n))" ;;
        *) : ;;
    esac
}

pass=0; fail=0
check() {
    local what="$1" want="$2" got="$3"
    if [[ "${want}" == "${got}" ]]; then
        printf '  ok   %s\n' "${what}"; pass=$((pass + 1))
    else
        printf '  FAIL %s: want %q, got %q\n' "${what}" "${want}" "${got}"
        fail=$((fail + 1))
    fi
}

make_peer() {
    local name="$1" addr="$2" key="$3"
    cat > "${GROXY_DIR}/portal/bridges/${name}.peer" <<EOF
# bridge "${name}" — generated by groxy test
PSK=$(fake_key 600)
BRIDGE_IP=${addr}
PUBLIC_KEY=${key}
EOF
}

KEY_A="$(fake_key 1)"
KEY_B="$(fake_key 2)"

echo "== один ключ — один пир =="
# Ядро держит один пир на ключ. Две записи с одним ключом дают конфиг, где
# вторая молча перезаписывает первую, а какая победит — зависит от алфавитного
# порядка имён файлов. Ровно так на sweden прожила пара moscow-test.
make_peer alpha 10.77.77.2 "${KEY_A}"
make_peer beta 10.77.77.3 ''
( portal_accept_bridge beta --pubkey="${KEY_A}" ) >/dev/null 2>&1; rc=$?
check "чужой ключ отвергнут отдельным кодом" 10 "${rc}"
check "запись beta не тронута" '' \
    "$(peer_field "${GROXY_DIR}/portal/bridges/beta.peer" PUBLIC_KEY)"
check "конфиг не перерендерен" 0 \
    "$(find "${TMPROOT}" -maxdepth 1 -name rendered | wc -l | tr -d ' ')"

echo "== свой ключ принимается =="
( portal_accept_bridge beta --pubkey="${KEY_B}" ) >/dev/null 2>&1; rc=$?
check "код возврата" 0 "${rc}"
check "ключ записан" "${KEY_B}" \
    "$(peer_field "${GROXY_DIR}/portal/bridges/beta.peer" PUBLIC_KEY)"
check "конфиг перерендерен" 1 \
    "$(find "${TMPROOT}" -maxdepth 1 -name rendered | wc -l | tr -d ' ')"

echo "== пиры синхронизируются, а не перезапускаются =="
# Перезапуск wg0 на портале рвёт туннели всех подключённых бриджей, а с ними
# зарубежный трафик их клиентов. Снятие одного мёртвого пира в Фазе 0 стоило
# ровно этого и потребовало объявленного окна.
check "синхронизация вызвана" 1 \
    "$(find "${TMPROOT}" -maxdepth 1 -name synced | wc -l | tr -d ' ')"
check "перезапуска не было" 0 \
    "$(find "${TMPROOT}" -maxdepth 1 -name restarted | wc -l | tr -d ' ')"

echo "== снятие пира тоже без перезапуска =="
rm -f "${TMPROOT}/synced"
( portal_remove_bridge alpha ) >/dev/null 2>&1; rc=$?
check "код возврата" 0 "${rc}"
check "синхронизация вызвана" 1 \
    "$(find "${TMPROOT}" -maxdepth 1 -name synced | wc -l | tr -d ' ')"
check "перезапуска не было" 0 \
    "$(find "${TMPROOT}" -maxdepth 1 -name restarted | wc -l | tr -d ' ')"

echo "== повтор с тем же ключом — не ошибка =="
# Приём того же ключа повторно идемпотентен: администратор мог не увидеть
# первый ответ.
rm -f "${TMPROOT}/rendered"
( portal_accept_bridge beta --pubkey="${KEY_B}" ) >/dev/null 2>&1; rc=$?
check "успех" 0 "${rc}"

echo "== смена ключа у того же пира требует снятия =="
( portal_accept_bridge beta --pubkey="$(fake_key 3)" ) >/dev/null 2>&1; rc=$?
check "отказ" 1 "${rc}"

echo "== поле пира не переопределяет переменные читающего =="
# Файл пира — состояние, а не код. Раньше он читался через `source`, и строка
# вида `name=` меняла переменную вызывающего.
cat > "${GROXY_DIR}/portal/bridges/evil.peer" <<EOF
# bridge "evil"
PSK=$(fake_key 601)
BRIDGE_IP=10.77.77.9
PUBLIC_KEY=$(fake_key 4)
name=подменено
EOF
( portal_accept_bridge evil --pubkey="$(fake_key 4)" ) >/dev/null 2>&1; rc=$?
check "принято без подмены" 0 "${rc}"
check "имя файла не изменилось" 1 \
    "$(find "${GROXY_DIR}/portal/bridges" -name 'evil.peer' | wc -l | tr -d ' ')"

echo
echo "прошло: ${pass}, упало: ${fail}"
rm -rf "${TMPROOT}"
[[ ${fail} -eq 0 ]]
